// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVB7S59FlMYgvXHNGspH-SNZ2ffzo7Kc',
    appId: '1:79772205925:web:46daab89f57921b1d6578c',
    messagingSenderId: '79772205925',
    projectId: 'academic-management-syst-5e9d8',
    authDomain: 'academic-management-syst-5e9d8.firebaseapp.com',
    storageBucket: 'academic-management-syst-5e9d8.firebasestorage.app',
    measurementId: 'G-DRV8EX8S42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVXB0nmfWw2pmry1S_Vf6CAVppo-P_O8',
    appId: '1:79772205925:android:590686c16b9603dcd6578c',
    messagingSenderId: '79772205925',
    projectId: 'academic-management-syst-5e9d8',
    storageBucket: 'academic-management-syst-5e9d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvK0tfggxJHvD1j7xu56L304OsDXES2cQ',
    appId: '1:79772205925:ios:9c1eaa3b4a3d4a99d6578c',
    messagingSenderId: '79772205925',
    projectId: 'academic-management-syst-5e9d8',
    storageBucket: 'academic-management-syst-5e9d8.firebasestorage.app',
    iosBundleId: 'com.example.academicAffairsManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvK0tfggxJHvD1j7xu56L304OsDXES2cQ',
    appId: '1:79772205925:ios:9c1eaa3b4a3d4a99d6578c',
    messagingSenderId: '79772205925',
    projectId: 'academic-management-syst-5e9d8',
    storageBucket: 'academic-management-syst-5e9d8.firebasestorage.app',
    iosBundleId: 'com.example.academicAffairsManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUVB7S59FlMYgvXHNGspH-SNZ2ffzo7Kc',
    appId: '1:79772205925:web:d1a2f73b94bd7d47d6578c',
    messagingSenderId: '79772205925',
    projectId: 'academic-management-syst-5e9d8',
    authDomain: 'academic-management-syst-5e9d8.firebaseapp.com',
    storageBucket: 'academic-management-syst-5e9d8.firebasestorage.app',
    measurementId: 'G-B9YJX5CGFW',
  );
}
