// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWdNoPXAPee0ySt1EIeBWA2qWcV7kTgRg',
    appId: '1:482522249835:web:2c1fa7b4ed8a6532044f2e',
    messagingSenderId: '482522249835',
    projectId: 'sales-shop-2026',
    authDomain: 'sales-shop-2026.firebaseapp.com',
    storageBucket: 'sales-shop-2026.firebasestorage.app',
    measurementId: 'G-YC7WYJ2N8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CnfSYjn6rApaaCknGi4AjKxAnSgp5WA',
    appId: '1:482522249835:android:4d2150f987374220044f2e',
    messagingSenderId: '482522249835',
    projectId: 'sales-shop-2026',
    storageBucket: 'sales-shop-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKoBtCvJTiGJy4baOnrYcmMezRyNHCu78',
    appId: '1:482522249835:ios:f4456e0e7776d8ae044f2e',
    messagingSenderId: '482522249835',
    projectId: 'sales-shop-2026',
    storageBucket: 'sales-shop-2026.firebasestorage.app',
    iosBundleId: 'com.example.academicAffairsManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKoBtCvJTiGJy4baOnrYcmMezRyNHCu78',
    appId: '1:482522249835:ios:f4456e0e7776d8ae044f2e',
    messagingSenderId: '482522249835',
    projectId: 'sales-shop-2026',
    storageBucket: 'sales-shop-2026.firebasestorage.app',
    iosBundleId: 'com.example.academicAffairsManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWdNoPXAPee0ySt1EIeBWA2qWcV7kTgRg',
    appId: '1:482522249835:web:2c1fa7b4ed8a6532044f2e',
    messagingSenderId: '482522249835',
    projectId: 'sales-shop-2026',
    authDomain: 'sales-shop-2026.firebaseapp.com',
    storageBucket: 'sales-shop-2026.firebasestorage.app',
    measurementId: 'G-YC7WYJ2N8S',
  );

}